# Generated by Django 3.1.2 on 2020-11-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True, unique=True, verbose_name='CANDIDATE ID')),
                ('username', models.CharField(max_length=135, verbose_name='FULL NAME')),
                ('city', models.CharField(max_length=135, verbose_name='CITY')),
                ('phone', models.CharField(max_length=135, verbose_name='MOBILE')),
                ('email', models.EmailField(blank=True, max_length=135, verbose_name='E-Mail')),
                ('apply_position', models.CharField(blank=True, max_length=135, verbose_name='APPLIED POSITION')),
                ('born_address', models.CharField(blank=True, max_length=135, verbose_name='ADDRESS')),
                ('gender', models.CharField(blank=True, max_length=135, verbose_name='SEX')),
                ('candidate_remark', models.CharField(blank=True, max_length=135, verbose_name='OTHER INFORMATION')),
                ('bachelor_school', models.CharField(blank=True, max_length=135, verbose_name='BACHELOR DEGREE')),
                ('master_school', models.CharField(blank=True, max_length=135, verbose_name='MASTER DEGREE')),
                ('phd_school', models.CharField(blank=True, max_length=135, verbose_name='PHD DEGREE')),
                ('major', models.CharField(blank=True, max_length=135, verbose_name='MAJOR')),
                ('degree', models.CharField(blank=True, choices=[('bachelor', 'bachelor'), ('master', 'master'), ('phd', 'phd')], max_length=135, verbose_name='DEGREE')),
                ('test_score_of_general_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='BASIC ABILITY TEST SCORE')),
                ('paper_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='WRITING TEST SCORE')),
                ('first_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='INITIAL TEST SCORE')),
                ('first_learning_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='LEARNING ABILITY SCORE')),
                ('first_professional_competency', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='PROFESSIONAL ABILITY SCORE')),
                ('first_advantage', models.TextField(blank=True, max_length=1024, verbose_name='ADVANTAGE')),
                ('first_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='DISADVANTAGE')),
                ('first_result', models.CharField(blank=True, choices=[('建议复试', '建议面试'), ('待定', '待定'), ('放弃', '放弃')], max_length=256, verbose_name='INITIAL RESULT')),
                ('first_recommend_position', models.CharField(blank=True, max_length=256, verbose_name='RECOMMEND POSITION')),
                ('first_interviewer', models.CharField(blank=True, max_length=256, verbose_name='INTERVIEWER')),
                ('first_remark', models.CharField(blank=True, max_length=135, verbose_name='FIRST REMARK')),
                ('second_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='SECOND TEST SCORE')),
                ('second_learning_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='LEARNING ABILITY SCORE')),
                ('second_professional_competency', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='PROFESSIONAL ABILITY SCORE')),
                ('second_pursue_of_excellence', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='PURSUE OF EXCELLENCE SCORE')),
                ('second_communication_ability', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='COMMUNICATION SKILL SCORE')),
                ('second_pressure_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='ANTI PRESSURE SCORE')),
                ('second_advantage', models.TextField(blank=True, max_length=1024, verbose_name='ADVANTAGE')),
                ('second_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='DISADVANTAGE')),
                ('second_result', models.CharField(blank=True, choices=[('建议录用', '建议录用'), ('待定', '待定'), ('放弃', '放弃')], max_length=256, verbose_name='SECOND RESULT')),
                ('second_recommend_position', models.CharField(blank=True, max_length=256, verbose_name='RECOMMEND POSITION')),
                ('second_interviewer', models.CharField(blank=True, max_length=256, verbose_name='INTERVIEWER')),
                ('second_remark', models.CharField(blank=True, max_length=135, verbose_name='SECOND REMARK')),
                ('hr_score', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR SCORE')),
                ('hr_responsibility', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR RESPONSIBILITY')),
                ('hr_communication_ability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='COMMUNICATION SKILL')),
                ('hr_logic_ability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR LOGIC ABILITY')),
                ('hr_potential', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR DEVELOPMENT POTENTIAL')),
                ('hr_stability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='HR STABILITY')),
                ('hr_advantage', models.TextField(blank=True, max_length=1024, verbose_name='ADVANTAGE')),
                ('hr_disadvantage', models.TextField(blank=True, max_length=1024, verbose_name='DISADVANTAGE')),
                ('hr_result', models.CharField(blank=True, max_length=256, verbose_name='HR FINAL RESULT')),
                ('hr_interviewer', models.CharField(blank=True, max_length=256, verbose_name='HR INTERVIEWER')),
                ('hr_remark', models.CharField(blank=True, max_length=256, verbose_name='HR FINAL REMARK')),
                ('creator', models.CharField(blank=True, max_length=256, verbose_name='CANDIDATE DATA CREATOR')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='CREATED DATE')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='UPDATE TIME')),
                ('last_editor', models.CharField(blank=True, max_length=256, verbose_name='LAST EDITOR')),
            ],
            options={
                'verbose_name': 'APPLICANT',
                'verbose_name_plural': 'APPLICANTS',
                'db_table': 'candidate',
            },
        ),
    ]
