# Generated by Django 3.1.2 on 2020-11-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='bachelor_school',
            field=models.CharField(blank=True, max_length=135, verbose_name='BACHELOR SCHOOL'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Phd', 'Phd')], max_length=135, verbose_name='DEGREE'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hr_result',
            field=models.CharField(blank=True, choices=[('建议录用', '建议录用'), ('待定', '待定'), ('放弃', '放弃')], max_length=256, verbose_name='HR FINAL RESULT'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='master_school',
            field=models.CharField(blank=True, max_length=135, verbose_name='MASTER SCHOOL'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phd_school',
            field=models.CharField(blank=True, max_length=135, verbose_name='PHD SCHOOL'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='test_score_of_general_ability',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='BASIC SCORE'),
        ),
    ]
